# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
networks:
  backend-network:
    name: tripborder-backend-networkprod
    external: true

secrets:
  nominatim_password:
    file: ./secrets/nominatim_password.txt
  db_password:
    file: ./secrets/db_password.txt
  tunnel_token:
    file: ./secrets/tunnel_token.txt

services:
  serverprod:
    command: sh -c "npx knex migrate:latest && npm run server" # migrate to latest database schema
    build: .
    expose:
    - "7777"
    volumes:
      - ./ssl:/ssl
    environment:
      NODE_ENV: production
      DB_HOST: dbprod
      DB_USER: nientaiho
      DB_NAME: tripborderdb
      SSL_CERTIFICATE_PATH: /ssl/tripborderbackend-cert.pem
      SSL_PRIVATE_KEY_PATH: /ssl/tripborderbackend-key.pem
    env_file:
      - .env.production
    secrets:
      - db_password
    networks:
      - backend-network
    depends_on:
      dbprod:
        condition: service_healthy

  dbprod:
    image: postgres:latest
    environment:
      POSTGRES_USER: nientaiho
      POSTGRES_DB: tripborderdb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nientaiho", "-d", "tripborderdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginxprod:
    image: nginx:alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - backend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - serverprod

# Run below command if permission denied for external drive
  # dot_clean -m /Volumes/SSDName/nominatim-data
  nominatimprod:
    image: mediagis/nominatim:5.1  # Pulls pre-built Nominatim with osm2pgsql/PostgreSQL (stable version; avoids manual builds).
    volumes:
      - nominatim-pg-data:/var/lib/postgresql/16/main  # Persists DB data (~500GB+ for planet; maps host path to container for durability).
      - nominatim-flatnode:/nominatim/flatnode  # Flatnode storage for efficient import (reduces RAM needs during osm2pgsql load).
      - nominatim-share:/nominatim/share  # Hosts PBF file (e.g., download planet-latest.osm.pbf here externally via wget).
      - ${HOME}/nominatim-data/share:/nominatim/share
    shm_size: '16g'
    mem_limit: '16g'
    cpus: 8
    environment:
      - PBF_PATH=/nominatim/share/TW-JP-US-regions.osm.pbf  # Path to OSM data inside container (example: points to downloaded planet file for full import).
      - THREADS=8  # Parallel threads for import (match your CPU cores; speeds up osm2pgsql processing, e.g., 16 cores halve time).
      - IMPORT_STYLE=extratags # Minimal import style (faster, lower resources; use 'extratags' for more data if needed).
        # admin: Only import administrative boundaries and places.
        # street: Like the admin style but also adds streets.
        # address: Import all data necessary to compute addresses down to house number level.
        # full: Default style that also includes points of interest.
        # extratags: Like the full style but also adds most of the OSM tags into the extratags column.
      - IMPORT_WIKIPEDIA=false
    entrypoint:
      - /bin/sh  #Arg 1: Shell binary
      - -c  # Arg 2: Flag to treat next arg as a command string (prevents direct arg parsing).
      - export NOMINATIM_PASSWORD=$(cat /run/secrets/nominatim_password) && exec /app/start.sh  # Arg 3: Command string to execute.
    secrets:
      - nominatim_password
    networks:
      - backend-network  # Joins existing network (allows proxy_pass by service name, e.g., http://nominatim:8080).
    depends_on:
      - serverprod
      - dbprod

volumes:
  nominatim-pg-data:  # nominatim PostgreSQL
  nominatim-flatnode:  # nominatim flatnode
  nominatim-share:     # nominatim share
  postgres_data_prod: # Define the named volume here
